---
outdir: test/data
outdir-prep: test/data/prep
experiments:
  - sample: Test1
    ref: test/data/hg19.fa
    intervals: test/data/target-regions.bed
    align: test/data/aligned-reads.bam
    calls:
      - name: gatk
        file: test/data/gatk-calls.vcf
        refcalls: false
      - name: freebayes
        file: test/data/freebayes-calls.vcf
        annotate: true
        filters:
          - HRun > 5.0
          - QD < 2.0
          - FS > 60.0
          - MQRankSum < -12.5
                
