---
experiments:
  - sample: Test1
    ref: test/data/hg19.fa
    intervals: test/data/target-regions.bed
    calls:
      - name: gatk
        file: test/data/gatk-calls.vcf
      - name: freebayes
        file: test/data/freebayes-calls.vcf
