---
dir:
  out: test/data/multi
  prep: test/data/multi/prep
experiments:
  - ref: test/data/GRCh37.fa
    params:
      multiple-thresh: 0.75
    calls:
      - name: c1
        metadata:
          caller: c1
        file: test/data/1000genome-multi.vcf
      - name: c2
        metadata:
          caller: c2
        file: test/data/1000genome-multi-cmp.vcf
